layout_spectrum: 0.002685252
color:
  saturation: 0.7731605
  lightness: 0.8104189
  brandStrength: 0.8243824
  brandColors:
    - '#000000'
    - '#271D1F'
    - '#783031'
    - '#FBE9E9'
    - '#B48891'
  rhythmicContrast: 0.7524167
typography_spectrum: 0
name: Adriatic video award 2016
