name: Adriatic video award 2016
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75098
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#783031'
    - '#241b1c'
    - '#fefdfe'
    - '#bd686d'
    - '#aaa5a6'
  brandStrength: 0.8995703
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
